//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchetGIC.DataFiles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UchetDBEntities : DbContext
    {
        public UchetDBEntities()
            : base("name=UchetDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<EmployeeObject> EmployeeObject { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<Leave> Leave { get; set; }
        public virtual DbSet<LocalServ> LocalServ { get; set; }
        public virtual DbSet<MealSchedule> MealSchedule { get; set; }
        public virtual DbSet<Objects> Objects { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Salary> Salary { get; set; }
        public virtual DbSet<SeasonalEmployee> SeasonalEmployee { get; set; }
        public virtual DbSet<SpecialClothing> SpecialClothing { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WorkTime> WorkTime { get; set; }
    }
}
