//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchetGIC.DataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTime
    {
        public int WorkTimeID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<System.TimeSpan> BreakTime { get; set; }
        public Nullable<System.TimeSpan> TotalTime { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
